language: node_js

node_js:
  - "4"

script:
  - npm run lint
  - npm run test:cov

after_success:
  - npm install coveralls
  - $(npm bin)/istanbul report lcov
  - cat ./coverage/lcov.info | $(npm bin)/coveralls
